apt_update 'Update the apt cache daily' do
  frequency 86_400
  action :periodic
end

package 'docker.io'

service 'docker' do
  supports status: true
  action [:enable, :start]
end

remote_file '/usr/local/bin/docker-compose' do
  source 'https://github.com/docker/compose/releases/download/1.20.1/docker-compose-Linux-x86_64'
  mode '0755'
  action :create
end

file '/home/resolv.conf' do
  content '# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 10.1.0.106
nameserver 10.1.0.2
search ec2.internal'
  mode '0644'
  owner 'root'
  group 'root'
end

file '/etc/resolv.conf' do
  action :delete
end

link '/etc/resolv.conf' do
  to '/home/resolv.conf'
end

directory '/home/sentinel' do
  owner 'root'
  group 'root'
  mode '0755'
  action :create
end

file '/home/sentinel/Dockerfile' do
  content 'FROM redis
EXPOSE 5000
ADD sentinel.conf /etc/redis/sentinel.conf
RUN chown redis:redis /etc/redis/sentinel.conf
COPY sentinel-entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/sentinel-entrypoint.sh
ENTRYPOINT ["sentinel-entrypoint.sh"]'
  group 'root'
  owner 'root'
  mode '0644'
end

file '/home/sentinel/sentinel.conf' do
  content 'port 5000

dir /tmp

sentinel monitor mymaster master.service.consul 6379 2

sentinel down-after-milliseconds mymaster 30000

sentinel parallel-syncs mymaster 1

sentinel failover-timeout mymaster 180000'
  group 'root'
  owner 'root'
  mode '0644'
end

file '/home/sentinel/sentinel-entrypoint.sh' do
  content '#!/bin/sh
exec docker-entrypoint.sh redis-server /etc/redis/sentinel.conf --sentinel'
  group 'root'
  owner 'root'
  mode '0755'
end

file '/home/docker-compose.yml' do
  content 'version: "3"

services:

  consul:
    image:  gliderlabs/consul-server:latest
    command: "-advertise=$LOCAL_IP -retry-join=10.1.0.106"
    container_name: consul
    ports:
     - "8500:8500"
     - "8300:8300"
     - "8400:8400"
     - "8301:8301/tcp"
     - "8302:8302/tcp"
     - "8301:8301/udp"
     - "8302:8302/udp"
     - "53:8600/udp"

  registrator:
    image: gliderlabs/registrator:latest
    command: "-ip $LOCAL_IP consul://$LOCAL_IP:8500"
    container_name: registrator
    depends_on:
    - consul
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock

  redisslave:
    container_name: redisslave
    image: redis
    command: redis-server --slaveof master.service.consul 6379
    ports:
      - 6379:6379
    restart: always
    depends_on:
      - registrator

  sentinel:
    build: sentinel
    environment:
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=5000
    depends_on:
      - redisslave'
end

execute 'docker-compose' do
  command 'w'
end
